views:
  - output: "sites.json"
    query: "sites.rq"
    template: "items.json"
    unsafe: true
  - output: "index.html"
    template: "index.html"
  - output: "site-type/{{id}}.html"
    query: "site-types.rq"
    template: "site-type.html"
