PREFIX for: <https://dkglab.github.io/ns/for/>
PREFIX kos: <https://dkglab.github.io/ns/for/kos/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wiki: <https://www.wikidata.org/entity/>
PREFIX ple: <https://pleiades.stoa.org/vocabularies/place-types/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


# SELECT ?uri ?ceramic_type ?id WHERE {
SELECT ?uri ?ceramic_type ?id ?wiki_entity ?form_type ?start_date ?end_date ?suggested_dating ?ARSGroup ?ARSGroup2 ?ARSImportHorizon ?ARSImportHorizon2 WHERE {
  ?uri
    rdf:type skos:Concept ;
    skos:inScheme kos:ceramic-types ;
    dcterms:identifier ?id ;
    skos:prefLabel ?ceramic_type .
    BIND(xsd:integer(REPLACE(?id, "[^0-9]", ""))AS ?numid)
    OPTIONAL { ?uri skos:exactMatch ?wiki_entity . }
    OPTIONAL { ?uri skos:definition ?form_type . }
    OPTIONAL { ?uri dcterms:temporal ?start_date . }
    OPTIONAL { ?uri dcterms:temporal ?end_date . }
    OPTIONAL { ?uri skos:note ?suggested_dating . }
    OPTIONAL { ?uri kos:ARSGroup ?ARSGroup . }
    OPTIONAL { ?uri kos:ARSGroup2 ?ARSGroup2 . }
    OPTIONAL { ?uri kos:ARSImportHorizon ?ARSImportHorizon . }
    OPTIONAL { ?uri kos:ARSImportHorizon2 ?ARSImportHorizon . }
}
ORDER BY (?numid)