PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX for:     <https://dkglab.github.io/ns/for/>
PREFIX geo:     <http://www.opengis.net/ont/geosparql#>
PREFIX pno:     <http://linked.data.gov.au/def/placenames/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?municipality ?municipality_label ?municipality_place_name_for_uri 
       ?municipality_wiki_uri ?municipality_viaf_uri ?municipality_geonames_uri ?wktLiteral ?description
WHERE {
  ?municipality a pno:Place ;
                rdfs:label ?municipality_label ;
                pno:hasPlaceName ?municipality_place_name_for_uri ;
                dcterms:identifier ?municipality_wiki_uri , ?municipality_viaf_uri , ?municipality_geonames_uri ;
                dcterms:description ?description ;
                geo:hasGeometry [ geo:asWKT ?wktLiteral ] .
}
ORDER BY ?municipality_label