PREFIX for: <https://dkglab.github.io/ns/for/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wiki: <https://www.wikidata.org/entity/>
PREFIX ple: <https://pleiades.stoa.org/vocabularies/place-types/>

select ?uri ?site_type ?dcterm_id where {
    ?uri rdf:type skos:Concept ;
        dcterms:identifier ?dcterm_id ;
        skos:prefLabel ?site_type .

    filter(CONTAINS(STR(?uri), "site-type"))
}
order by LCASE(?site_type)