PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX for: <https://dkglab.github.io/ns/for/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT 
?id 
?site_name 
?processed 
# ?mct 
?towns 
#?site_type 
#?actualMuni 
WHERE {
  for:located-sites rdfs:member ?site .

  ?site a geo:Feature ;
    skos:prefLabel ?site_name ;
    skos:altLabel ?processed ;
#    for:hasArtifactType ?mct ;
    for:towns ?towns ;
  #  for:siteType ?siteType ;
  #  for:municipality ?actualMuni ;
    .

  BIND(STRAFTER(STR(?site), CONCAT(STR(for:site), "/")) AS ?id)
}
ORDER BY LCASE(?site_name)
