PREFIX for: <https://dkglab.github.io/ns/for/>
PREFIX kos: <https://dkglab.github.io/ns/for/kos/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wiki: <https://www.wikidata.org/entity/>
PREFIX ple: <https://pleiades.stoa.org/vocabularies/place-types/>

SELECT ?uri ?site_type ?id ?siteTypeDefinition ?wikiEntity ?pleiadesPlaceType ?broaderSiteType ?narrowerSiteType
WHERE {
  ?uri
    rdf:type skos:Concept ;
    skos:inScheme kos:site-types ;
    dcterms:identifier ?id ;
    skos:prefLabel ?site_type ;
    .

  OPTIONAL { ?uri skos:definition ?siteTypeDefinition .}
  OPTIONAL { ?uri skos:closeMatch ?wikiEntity .}
  OPTIONAL { ?uri skos:closeMatch ?pleiadesPlaceType .}
  #closeMatch returns either wiki or pleiades but not both 
  OPTIONAL { ?uri skos:broader ?broaderSiteType .}

 # trying to add a variable for narrower site type, but these don't work: 
  #OPTIONAL { ?narrowerSiteType 
                #skos:broader ?broaderSiteType
                #skos:inScheme kos:site-types ; 
                #.} 

  #OPTIONAL { ?broaderSiteType skos:narrower ?narrowerSiteType .}
  #OPTIONAL { ?uri skos:narrower ?narrowerSiteType .}

#to add: additional definitions from pleiades and wikidata

} 
#group by ? 
order by LCASE(?site_type)

