PREFIX dct: <http://purl.org/dc/terms/>
PREFIX for:     <https://dkglab.github.io/ns/for/>
PREFIX geo:     <http://www.opengis.net/ont/geosparql#>
PREFIX pno:     <http://linked.data.gov.au/def/placenames/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT
?id
?municipality_label
?wkt
WHERE {
  ?municipality a pno:Place ;
                dct:identifier ?id ;
                rdfs:label ?municipality_label ;
                geo:hasGeometry [ geo:asWKT ?wkt ] .
}
ORDER BY ?municipality_label