PREFIX for: <https://dkglab.github.io/ns/for/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX pno: <http://linked.data.gov.au/def/placenames/>

SELECT ?wkt
WHERE {
    for:analytic-regions a geo:FeatureCollection ;
        rdfs:member ?reg
        .

    ?reg a geo:Feature ;
        skos:prefLabel "Valencian Coast" ;
        geo:hasGeometry ?reggeo ;
        .
    ?reggeo geo:asWKT ?regwkt .
    
    for:located-sites rdfs:member ?site .

    ?site a geo:Feature ;
        geo:hasGeometry ?geo ;
        for:siteType ?site_type ;
        .

    ?geo geo:asWKT ?wkt .

    filter(
        geof:sfWithin(?wkt, ?regwkt)
    )

}