PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX for: <https://dkglab.github.io/ns/for/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
#PREFIX wiki: <https://www.wikidata.org/entity/>
#PREFIX ple: <https://pleiades.stoa.org/vocabularies/place-types/>

CONSTRUCT {
  ?SiteType a skos:Concept ; 
        skos:prefLabel ?prefLabel ;
        dcterms:identifier ?id ;
        skos:broader ?analysisSiteType ;
        skos:exactMatch ?wikiEntity ;
        skos:closeMatch ?pleiadesEntity.

  ?analysisSiteType a skos:Concept ; 
        skos:prefLabel ?analysisSiteTypeLabel ;
        #dcterms:identifier ?id ;
        skos:narrower ?SiteType ;
        skos:definition ?analysisSiteTypeDef.

}
WHERE {
  SERVICE <x-sparql-anything:> {
    fx:properties fx:csv.headers "true" .

    ?row xyz:ID ?id ; 
         xyz:prefLabel ?prefLabel;
         xyz:Analysis_Site_Type ?analysisSiteType;
         xyz:Analysis_Site_Type ?analysisSiteTypeLabel;
         xyz:wiki_id ?wikiId;
         xyz:pleiades_place ?pleiades_place;
         xyz:Analysis_Site_Type_Desc ?analysisSiteTypeDef.

    BIND(REPLACE(?id, " ", "") AS ?id2)
    BIND(fx:entity(for:, "site-type/", ?id2) as ?SiteType)

    BIND(IF(STRLEN(STR(?wikiId)) > 0, 
    fx:entity(<https://www.wikidata.org/entity/>, ?wikiId), 
    "" ) AS ?wikiEntity)
    
    BIND(IF(STRLEN(STR(?pleiades_place)) > 0, 
    fx:entity(<https://pleiades.stoa.org/vocabularies/place-types/>, ?pleiades_place), 
    "" ) AS ?pleiadesEntity)

#tried to use wiki and ple prefixes but it didn't work --maybe need a value in the middle like "site-type/"?

    #BIND(IF(STRLEN(STR(?wikiId)) > 0, 
    #fx:entity(wiki:, ?wikiId), 
    #"" ) AS ?wikiEntity)
    
    #BIND(IF(STRLEN(STR(?pleiades_place)) > 0, 
    #fx:entity(ple:, ?pleiades_place), 
    #"" ) AS ?pleiadesEntity)

#To Do:
#1 how incorporate analysis site type descriptions - would we use skos:inScheme 
  #to create a site types scheme and analysis site types scheme, linked by skos:broader? 

#2 use REPLACE to remove spaces by replacing spaces with empty strings for uris 

#revisit function for blank nodes: 

    #BIND(IF(BOUND(?wikiId) && STRLEN(STR(?wikiId))>0,
          #fx:entity(<https://www.wikidata.org/entity/>, ?wikiId),
          #BNODE()) AS ?wikiEntity)
    
    #BIND(IF(BOUND(?pleiades_place) && STRLEN(STR(?pleiades_place))>0,
          #fx:entity(<https://pleiades.stoa.org/vocabularies/place-types/>, ?pleiades_place),
          #BNODE()) AS ?pleiadesEntity)
  }
}
