name: validate RDF
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate-rdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: devcontainers/ci@v0.3
        with: 
          runCmd: make graph
